openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API
    url: 'https://virtserver.swaggerhub.com/CHAIYAPONGAP/PhaseHub/1.0.0'
info:
  description: 'This is a PhaseHub API '
  version: 1.0.0
  title: PhaseHub API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: products
    description: API for product
  - name: cases
    description: API for case (order)
  - name: shipments
    description: API for shipment
paths:
  /products:
    get:
      summary: list products
      tags:
        - products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    x-stoplight:
                      id: 9vjhk1zx5incb
                    properties:
                      data:
                        type: array
                        x-stoplight:
                          id: 381e2j4dhvj9h
                        items:
                          $ref: '#/components/schemas/Product'
              examples:
                Success:
                  value:
                    message: Request successful
                    success: true
                    data:
                      - code: BCA
                        name: Brius Clear Aligner
                        productType: Aligner
                      - code: OFX
                        name: OFX-Aligner
                        productType: Aligner
                      - code: BCR
                        name: Brius Clear Retainer (.76)
                        productType: Retainer
      operationId: list-products
  /cases:
    parameters: []
    post:
      summary: create a case
      tags:
        - cases
      requestBody:
        description: Case to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Case'
            examples: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                  - type: object
                    x-stoplight:
                      id: zx60yyddnp9yb
                    properties:
                      data:
                        type: object
                        x-stoplight:
                          id: h180illrktgh1
                        properties:
                          referenceId:
                            type: string
                            x-stoplight:
                              id: bpxy7mhp137oo
                            example: dfghj2bf9cs56fgsd
              examples: {}
        '400':
          description: 'invalid input, object invalid'
      operationId: create-case
      description: create a case to the system
  '/cases/{referenceId}/upload':
    parameters:
      - schema:
          type: string
          example: dfghj2bf9cs56fgsd
        name: referenceId
        in: path
        required: true
    post:
      summary: upload STL file
      tags:
        - cases
      responses:
        '200':
          description: file upoaded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
              examples: {}
        '400':
          description: 'invalid input, object or file invalid'
        '404':
          description: case not found
      operationId: upload-file
      description: upload .stl file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                stepType:
                  type: string
                  example: maxilla
                step:
                  type: string
                  example: 1-0
                file:
                  type: string
                  format: binary
            encoding:
              stlFile:
                contentType: 'application/octet-stream, application/zip'
  '/cases/{referenceId}/submit':
    parameters:
      - schema:
          type: string
          example: dfghj2bf9cs56fgsd
        name: referenceId
        in: path
        required: true
    post:
      summary: submit the case
      tags:
        - cases
      responses:
        '200':
          description: case submitted
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
              examples: {}
        '400':
          description: 'invalid input, object invalid'
        '404':
          description: case not found
      operationId: submit-case
      description: submit the case
  '/shipments/{caseId}':
    parameters:
      - schema:
          type: string
        name: caseId
        in: path
        required: true
    post:
      summary: create shipment
      tags:
        - shipments
      requestBody:
        description: Shipment to create
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Shipment'
      responses:
        '201':
          description: Created
        '400':
          description: 'invalid input, object invalid'
        '404':
          description: case not found
      operationId: create-shipment
      description: Create shipment for the specific case
components:
  schemas:
    BaseResponse:
      title: BaseResponse
      type: object
      x-examples:
        Example 1:
          message: Request successful
          success: true
      properties:
        message:
          type: string
          x-stoplight:
            id: ch53fxz5pkxxz
          example: Request successful
        success:
          type: boolean
          x-stoplight:
            id: 1j33hnjtf759y
          default: true
    Case:
      type: object
      x-examples:
        Example 1:
          clinicId: 659f84bf50fdcfa81d600a9c
          doctorName: XXXXXXXXXX
          doctorEmail: doctorpo@inteware.com.tw
          caseId: 669faab5497a45276e46122b
          orderId: 66c2e483b2ca506ca3176844
          patientId: 93415931A
          patientFirstname: Tony
          patientLastname: Jaa
          deliveryName: Phase Ortho company
          deliveryAddress1: 2501 Stanley Gault Pkwy
          deliveryAddress2: ABC Building room39
          deliveryCity: Taipei
          deliveryState: California
          deliveryZipCode: '50390'
          deliveryCountry: USA
          dueDate: '2024-12-31'
          doctorNote: Please contact me back
          maxillaSteps:
            - step: 1-0
              productCode:
                - PCOA
            - step: '1'
              productCode:
                - PCOA
            - step: '2'
              productCode:
                - PCOA
          mandibleSteps:
            - step: 1-0
              productCode:
                - PCOA
            - step: '1'
              productCode:
                - PCOA
      properties:
        clinicId:
          type: string
          example: 659f84bf50fdcfa81d600a9c
        doctorName:
          type: string
          example: Doctorpo
        doctorEmail:
          type: string
          example: doctorpo@inteware.com.tw
        caseId:
          type: string
          example: 669faab5497a45276e46122b
        orderId:
          type: string
          example: 66c2e483b2ca506ca3176844
        patientId:
          type: string
          example: 93415931A
        patientFirstname:
          type: string
          example: Tony
        patientLastname:
          type: string
          example: Jaa
        deliveryName:
          type: string
          example: Phase Ortho company
        deliveryAddress1:
          type: string
          example: 2501 Stanley Gault Pkwy
        deliveryAddress2:
          type: string
          example: ABC Building room39
        deliveryCity:
          type: string
          example: Taipei
        deliveryState:
          type: string
          example: California
        deliveryZipCode:
          type: string
          example: '50390'
        deliveryCountry:
          type: string
          example: USA
        dueDate:
          type: string
          format: date
          example: '2024-12-31'
        doctorNote:
          type: string
          example: Please contact me back
        maxillaSteps:
          type: array
          items:
            type: object
            properties:
              step:
                type: string
                example: 1-0
              attachment:
                type: boolean
                example: true
              products:
                type: array
                example:
                  - PCOA
                items:
                  type: string
        mandibleSteps:
          type: array
          items:
            type: object
            properties:
              step:
                type: string
                example: 1-0
              attachment:
                type: boolean
                example: false
              products:
                type: array
                example:
                  - PCOA
                items:
                  type: string
    Product:
      title: Product
      type: object
      properties:
        code:
          type: string
        name:
          type: string
          x-stoplight:
            id: aecu04poe97gi
        productType:
          type: string
          x-stoplight:
            id: iuw3j87rai3uz
    Shipment:
      title: Shipment
      type: object
      x-examples: {}
      properties:
        caseId:
          type: string
          example: '115345'
        caseCharge:
          type: number
          x-stoplight:
            id: vou2c6cxw19mf
          format: float
          example: 99.55
        allignerThickness:
          type: array
          x-stoplight:
            id: purucyc4iusaw
          items:
            x-stoplight:
              id: rk89h2b9moltf
            type: object
            properties:
              shade:
                type: string
                example: U01
              thickness:
                type: number
                x-stoplight:
                  id: 7lbcdb8hwf02h
                format: float
                example: 0.25
        shippingInfo:
          type: string
          x-stoplight:
            id: jfdytdc1gzumw
          example: US1233445
        shippingRemark:
          type: string
          x-stoplight:
            id: i62j09fc3y6ba
          example: Some remark
        shippingPhoto:
          type: string
          x-stoplight:
            id: ps81iv2jhbygh
          format: binary
        shippingDocument:
          type: string
          x-stoplight:
            id: gbd7iuzpstx5f
          format: binary
  responses: {}
  securitySchemes:
    apiKey_1:
      name: apiKey
      type: apiKey
      in: query
